### ISSUE TITLE
To-do!

### ISSUE THREAD

**Issue by luca1s** [InfiniteRadar/Infinite-Radar#1]
- [x] Add close button for info panel
- [ ] add aircraft image
- [x] add user details
